### get all blogs
GET http://localhost:3003/api/blogs HTTP/1.1

### post a blog
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "I am cumming",
  "author": "ash",
  "url": "jav.com",
  "likes": 114514
}